//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren1_Plekhankov.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int id { get; set; }
        public string name_company { get; set; }
        public string type_agent { get; set; }
        public string ur_adres { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string FIO_director { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string logorip { get; set; }
        public int prioritet { get; set; }
    }
}
