//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren1_Plekhankov.DateBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tren1_PlekhankovEntities : DbContext
    {

        private static tren1_PlekhankovEntities _context;
        public tren1_PlekhankovEntities()
            : base("name=tren1_PlekhankovEntities")
        {
        }

        public static tren1_PlekhankovEntities GetContext()
        {
            if (_context == null)
                _context = new tren1_PlekhankovEntities();

            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Postavchik> Postavchik { get; set; }
        public virtual DbSet<Postavka> Postavka { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
